/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as InstitutionSetupRouteImport } from './routes/institution-setup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as VerifyStudentRouteImport } from './routes/verify-student'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as ApiPaymentCancelRouteImport } from './routes/api/payment/cancel'
import { Route as ApiPaymentFailRouteImport } from './routes/api/payment/fail'
import { Route as ApiPaymentSuccessRouteImport } from './routes/api/payment/success'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const InstitutionSetupRoute = InstitutionSetupRouteImport.update({
  id: '/institution-setup',
  path: '/institution-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyStudentRoute = VerifyStudentRouteImport.update({
  id: '/verify-student',
  path: '/verify-student',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPaymentCancelRoute = ApiPaymentCancelRouteImport.update({
  id: '/api/payment/cancel',
  path: '/api/payment/cancel',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentFailRoute = ApiPaymentFailRouteImport.update({
  id: '/api/payment/fail',
  path: '/api/payment/fail',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentSuccessRoute = ApiPaymentSuccessRouteImport.update({
  id: '/api/payment/success',
  path: '/api/payment/success',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/institution-setup': typeof InstitutionSetupRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify-student': typeof VerifyStudentRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/api/payment/cancel': typeof ApiPaymentCancelRoute
  '/api/payment/fail': typeof ApiPaymentFailRoute
  '/api/payment/success': typeof ApiPaymentSuccessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/institution-setup': typeof InstitutionSetupRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify-student': typeof VerifyStudentRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/api/payment/cancel': typeof ApiPaymentCancelRoute
  '/api/payment/fail': typeof ApiPaymentFailRoute
  '/api/payment/success': typeof ApiPaymentSuccessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/institution-setup': typeof InstitutionSetupRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify-student': typeof VerifyStudentRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/api/payment/cancel': typeof ApiPaymentCancelRoute
  '/api/payment/fail': typeof ApiPaymentFailRoute
  '/api/payment/success': typeof ApiPaymentSuccessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/institution-setup'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/verify-student'
    | '/dashboard'
    | '/api/payment/cancel'
    | '/api/payment/fail'
    | '/api/payment/success'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/institution-setup'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/verify-student'
    | '/dashboard'
    | '/api/payment/cancel'
    | '/api/payment/fail'
    | '/api/payment/success'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/institution-setup'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/verify-student'
    | '/_authenticated/dashboard'
    | '/api/payment/cancel'
    | '/api/payment/fail'
    | '/api/payment/success'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  InstitutionSetupRoute: typeof InstitutionSetupRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  VerifyStudentRoute: typeof VerifyStudentRoute
  ApiPaymentCancelRoute: typeof ApiPaymentCancelRoute
  ApiPaymentFailRoute: typeof ApiPaymentFailRoute
  ApiPaymentSuccessRoute: typeof ApiPaymentSuccessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/institution-setup': {
      id: '/institution-setup'
      path: '/institution-setup'
      fullPath: '/institution-setup'
      preLoaderRoute: typeof InstitutionSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-student': {
      id: '/verify-student'
      path: '/verify-student'
      fullPath: '/verify-student'
      preLoaderRoute: typeof VerifyStudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/payment/cancel': {
      id: '/api/payment/cancel'
      path: '/api/payment/cancel'
      fullPath: '/api/payment/cancel'
      preLoaderRoute: typeof ApiPaymentCancelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payment/fail': {
      id: '/api/payment/fail'
      path: '/api/payment/fail'
      fullPath: '/api/payment/fail'
      preLoaderRoute: typeof ApiPaymentFailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payment/success': {
      id: '/api/payment/success'
      path: '/api/payment/success'
      fullPath: '/api/payment/success'
      preLoaderRoute: typeof ApiPaymentSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  InstitutionSetupRoute: InstitutionSetupRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  VerifyStudentRoute: VerifyStudentRoute,
  ApiPaymentCancelRoute: ApiPaymentCancelRoute,
  ApiPaymentFailRoute: ApiPaymentFailRoute,
  ApiPaymentSuccessRoute: ApiPaymentSuccessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
